drupal_base_url: 'http://localhost:8000/node/'
fedora_base_url: 'http://localhost:8080/fcrepo/rest/'

# How to name the Bag directory (or file if serialized). One of 'nid' or 'uuid'.
bag_name: nid
temp_dir: /tmp/islandora_bagger_temp
output_dir: /home/mark/islandora_bagger

# Whether or not to zip up the Bag. One of false, 'zip', or 'tgz'.
# serialize: zip
serialize: false

# Include Internal-Sender-Identifier and Bagging-Date tags.
include_basic_baginfo_tags: true

# You can use any combination of additional tag name / value here.
bag-info:
    Contact-Name: Mark Jordan
    Contact-Email: bags@sfu.ca
    Source-Organization: Simon Fraser University
    Foo: Bar

# Whether or not to log Bag creation.
log_bag_creation: true
